[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:486 checking whether the connectivity to the database is working
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:491 Cutting network for postgresql/1
[32mINFO    [0m pytest_operator.plugin:plugin.py:834 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.1.7    unsupported  02:21:11Z

App                  Version  Status  Scale  Charm                Channel  Rev  Exposed  Message
postgresql           14.11    active    2/3  postgresql                      0  no       Primary
postgresql-test-app           active      1  postgresql-test-app  edge     127  no       received database credentials of the first database

Unit                    Workload  Agent  Machine  Public address  Ports     Message
postgresql-test-app/0*  active    idle   3        10.57.201.131             received database credentials of the first database
postgresql/1            unknown   lost   1        10.57.201.150   5432/tcp  agent lost, see 'juju show-status-log postgresql/1'
postgresql/2*           active    idle   2        10.57.201.62    5432/tcp  
postgresql/3            active    idle   4        10.57.201.130   5432/tcp  

Machine  State    Address        Inst id        Base          AZ  Message
1        down     10.57.201.150  juju-44067b-1  ubuntu@22.04      Running
2        started  10.57.201.62   juju-44067b-2  ubuntu@22.04      Running
3        started  10.57.201.131  juju-44067b-3  ubuntu@22.04      Running
4        started  10.57.201.130  juju-44067b-4  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:840 Juju error logs:

machine-1: 01:30:19 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:30:19 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-1: 01:30:19 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-1: 01:30:19 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 01:30:21 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:30:21 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:30:21 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
unit-postgresql-0: 01:30:21 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:30:23 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:30:23 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:30:23 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
unit-postgresql-test-app-0: 01:30:23 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:30:24 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:30:24 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:30:24 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
unit-postgresql-2: 01:30:24 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-4: 01:44:03 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:44:03 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-4: 01:44:03 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-3: 01:44:03 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-1: 01:49:20 ERROR unit.postgresql/1.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.130", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 01:52:20 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:52:24 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:52:28 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:52:32 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:52:36 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:52:40 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:52:44 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:52:48 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:52:52 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:52:56 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:53:00 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:53:04 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:53:08 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:53:12 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:53:16 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:53:20 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:53:24 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:53:28 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:53:33 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:53:37 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:53:41 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:53:45 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:53:49 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:53:53 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:53:57 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:54:01 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:54:05 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:54:09 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:54:13 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:54:17 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:54:21 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:54:25 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:54:29 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:54:33 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:54:37 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:54:41 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:54:45 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:54:49 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:54:53 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:54:57 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:55:01 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:55:05 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:55:09 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:55:13 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:55:17 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:55:21 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:55:25 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:55:29 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:55:33 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:55:37 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:55:41 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:55:45 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:55:49 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:55:53 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:55:57 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:56:01 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:56:05 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:56:09 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:56:13 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:56:18 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:56:22 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:56:26 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:56:30 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:56:34 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:56:38 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:56:42 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:56:46 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:56:50 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:56:54 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:56:58 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:57:02 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:57:06 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:57:10 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:57:14 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-test-app-0: 01:57:18 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-1: 02:06:34 ERROR unit.postgresql/1.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.117", port 5432 failed: timeout expired

unit-postgresql-1: 02:06:43 ERROR unit.postgresql/1.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.117", port 5432 failed: timeout expired

unit-postgresql-1: 02:06:50 ERROR unit.postgresql/1.juju-log Failed to list PostgreSQL database users: could not translate host name "None" to address: Temporary failure in name resolution

machine-2: 02:07:53 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: api connection broken unexpectedly
unit-postgresql-test-app-0: 02:16:14 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:16:14 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
machine-1: 02:16:49 ERROR juju.worker.dependency "migration-minion" manifold worker returned unexpected error: connection is shut down
machine-1: 02:16:49 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: connection is shut down
machine-1: 02:16:49 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: api connection broken unexpectedly
unit-postgresql-test-app-0: 02:17:18 ERROR unit.postgresql-test-app/0.juju-log Unable to read result
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 371, in _stop_continuous_writes
    with open(LAST_WRITTEN_FILE, "r") as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/last_written_value'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 369, in _stop_continuous_writes
    for attempt in Retrying(stop=stop_after_delay(60), wait=wait_fixed(5)):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/tenacity/__init__.py", line 435, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/tenacity/__init__.py", line 368, in iter
    result = action(retry_state)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/tenacity/__init__.py", line 411, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7fca6e3a6320 state=finished raised FileNotFoundError>]
unit-postgresql-test-app-0: 02:17:23 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:17:23 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-test-app-0: 02:17:32 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:17:32 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-test-app-0: 02:17:41 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:17:41 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-test-app-0: 02:17:50 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:17:50 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-test-app-0: 02:17:59 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:17:59 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-2: 02:18:00 ERROR unit.postgresql/2.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-2: 02:18:03 ERROR unit.postgresql/2.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:18:08 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:18:08 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-2: 02:18:09 ERROR unit.postgresql/2.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:18:17 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:18:17 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-2: 02:18:19 ERROR unit.postgresql/2.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:18:26 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:18:26 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-2: 02:18:31 ERROR unit.postgresql/2.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:18:35 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:18:35 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-2: 02:18:39 ERROR unit.postgresql/2.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:18:45 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:18:45 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-2: 02:18:49 ERROR unit.postgresql/2.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:18:54 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:18:54 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-2: 02:18:59 ERROR unit.postgresql/2.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:19:03 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:19:03 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-2: 02:19:09 ERROR unit.postgresql/2.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:19:12 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:19:12 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-2: 02:19:20 ERROR unit.postgresql/2.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:19:21 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:19:21 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-test-app-0: 02:19:30 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:19:30 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-2: 02:19:30 ERROR unit.postgresql/2.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-2: 02:19:39 ERROR unit.postgresql/2.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:19:39 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:19:39 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-test-app-0: 02:19:48 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:19:48 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-2: 02:19:50 ERROR unit.postgresql/2.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:19:57 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:19:57 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-2: 02:20:02 ERROR unit.postgresql/2.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:20:06 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:20:06 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-2: 02:20:12 ERROR unit.postgresql/2.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:20:15 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:20:15 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-2: 02:20:22 ERROR unit.postgresql/2.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:20:24 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:20:24 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-2: 02:20:31 ERROR unit.postgresql/2.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:20:33 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:20:33 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-2: 02:20:41 ERROR unit.postgresql/2.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:20:42 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:20:42 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-2: 02:20:51 ERROR unit.postgresql/2.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:20:51 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:20:51 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-2: 02:20:59 ERROR unit.postgresql/2.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:21:00 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 281, in _on_clear_continuous_writes_action
    with psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.57.201.150", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:21:00 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 290, in _on_clear_continuous_writes_action
    connection.close()
UnboundLocalError: local variable 'connection' referenced before assignment
unit-postgresql-2: 02:21:07 ERROR unit.postgresql/2.juju-log Failed to list PostgreSQL database users: connection to server at "10.57.201.150", port 5432 failed: timeout expired


[32mINFO    [0m pytest_operator.plugin:plugin.py:904 Forgetting main...